# Generated by Django 6.0 on 2025-12-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=12)),
                ('role', models.CharField(choices=[('user', 'user'), ('reseller', 'reseller')], default='user')),
                ('address', models.CharField(default=' ', max_length=200)),
                ('mobile_number', models.IntegerField(default=100)),
                ('profile_pic', models.CharField(default=' ')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
