# Generated by Django 6.0 on 2025-12-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='user_id',
            new_name='id',
        ),
    ]
