# Generated by Django 6.0 on 2025-12-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_id_accounts_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='id',
            new_name='user_id',
        ),
    ]
