# Generated by Django 6.0 on 2025-12-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_id_accounts_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='user_id',
            new_name='id',
        ),
    ]
